import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar';

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>GameReview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.jpeg" />
      </Head>
      <video className={styles.bg} loop autoPlay muted poster="videobg.mp4"><source src="videobg.mp4" type="video/mp4"></source></video>

      <div className={styles.navbar}>
        <Navbar></Navbar>
      </div>



      <div className={styles.header}>
        <h1 className={styles.title}>
          GameReview
        </h1>
      </div>

      <div>
        <footer className={styles.footer}>
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Made by Bunjee Awoyomi aoa26 and Giles Mitchell gm456{' '}
          </a>
        </footer>
      </div>

    </div>
  )
}
